// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axwijbanqhhjxicljwec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4d2lqYmFucWhoanhpY2xqd2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjg2NDcsImV4cCI6MjA2NDY0NDY0N30.VZUwmfLOdJxJtn-gqHscHyu5VUayxpOhHXdKCbgkB9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);